# Generated by Django 4.1.13 on 2024-05-09 03:16

from django.conf import settings
from django.db import migrations


def init_user_msg_subscription(apps, schema_editor):
    User = apps.get_model('users', 'User')
    UserMsgSubscription = apps.get_model('notifications', 'UserMsgSubscription')

    receive_backends = ['site_msg', 'email']
    user = User.objects.filter(username='admin').first()
    if not user:
        return
    UserMsgSubscription.objects.update_or_create(
        defaults={'receive_backends': receive_backends}, user=user
    )



class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(init_user_msg_subscription)
    ]
