# Generated by Django 4.1.13 on 2025-03-04 07:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Updated by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Comment')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('name', models.CharField(max_length=1024, verbose_name='Name')),
                ('spu', models.CharField(max_length=128, verbose_name='SPU')),
                ('type', models.CharField(max_length=128, verbose_name='Type')),
                ('skc', models.CharField(max_length=128, verbose_name='SKC')),
                ('sku', models.CharField(max_length=128, unique=True, verbose_name='SKU')),
                ('number', models.CharField(max_length=128, verbose_name='Number')),
                ('avatar_url', models.URLField(max_length=1024, verbose_name='Avatar URL')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price')),
            ],
            options={
                'verbose_name': 'Product',
            },
        ),
    ]
