# Generated by Django 4.1.13 on 2025-03-06 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='business_number',
            field=models.CharField(max_length=128, unique=True, verbose_name='Business Number'),
        ),
    ]
